baseURL = "https://mod3.show"
languageCode = "en-us"
title = "mod3"
theme = "diary"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 4
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/episodes"
name = "Episodes"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5